### ISSUE TITLE
请教一下 /base/FileUtil.cpp   中 为什么write函数使用fwrite_unlocked ？

### ISSUE THREAD

**Issue by bobbymly** [linyacool/WebServer#1]
fwrite_unlocked 是线程不安全的，这里为什么不使用 fwrite呢

**Comment by bobbymly** [comment]
是因为多个线程缓冲到同一个缓冲区里，只有这一个写入线程向文件中写入数据，所以负责写入文件的线程不需要线程安全是吗？

**Comment by linyacool** [comment]
@bobbymly 在FileUtil里的append函数已经要直接往文件里面写了，可以保证只有这一个线程写，所以不需要保证线程安全。不同线程Log会有竞态，往同一个缓冲区写的时候已经加过锁了(可以认为只有一个线程接收)，所以这里是安全的。这个log的设计我参考了muduo，但是简化了很多很多，只保留了基本思想，可以看下这里最后我总结了一下：https://github.com/linyacool/WebServer/blob/master/%E5%B9%B6%E5%8F%91%E6%A8%A1%E5%9E%8B.md
