### ISSUE TITLE
关于测试的问题

### ISSUE THREAD

**Issue by LinGar** [linyacool/WebServer#100]
你好，关于测试的结果我的是这样的
![Snipaste_2020-08-20_16-55-21](https://user-images.githubusercontent.com/46019794/90749415-03209f80-e306-11ea-91b6-60e6b1abaaf5.png)
我是在wsl上进行测试的用你的项目进行测试没有反应的不知道为什么
你在测试页面那里说吧日志关掉要如何关掉

**Comment by JimmyRowe13** [comment]
你好，我也遇到了这个问题，请问你还记得如何解决的吗，感谢
