### ISSUE TITLE
测得的短连接qps只有1万多

### ISSUE THREAD

**Issue by o555ddd** [linyacool/WebServer#106]
大神你好，我想复现你的qps测试结果，用了 “webbench -c 100 -t 10 http://本机地址/ ” 的参数进行测试，结果qps只有一万多？修改client数量和测试时间结果也是一万多，不知道您这个压测具体是要怎么复现呢？希望可以予以指教

**Comment by JarvistFth** [comment]
1000client， 60s， I7-4770 QPS 3w8左右。。我也很奇怪为啥。。

**Comment by linyacool** [comment]
@o555ddd @JarvistFth  我当时测完才加了"优雅关闭连接"的代码，会延迟关闭连接，导致webbench就不能配合测试了，https://github.com/linyacool/WebServer/issues/65  参考下这个，服务器不支持"优雅关闭连接"，就都没问题了

**Comment by o555ddd** [comment]
确实如此，感谢
