### ISSUE TITLE
关于opencv

### ISSUE THREAD

**Issue by vcdlk** [linyacool/WebServer#120]
编译oldversion0.1之前需要先安装opencv2吗？

**Comment by linyacool** [comment]
不需要的哈

**Comment by vcdlk** [comment]
我在requestData.cpp 文件下看到了

#include <opencv/cv.h>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/opencv.hpp>
using namespace cv;
这些代码，然后我编译错误（找不到这些文件），之后我编译安装了opencv2。现在正常了。。。。准备开始学习您的代码，谢谢您的回复^^

**Comment by linyacool** [comment]
@vcdlk 可以直接删掉吧，没有用到的，后面也忘记删了

**Comment by vcdlk** [comment]
@linyacool  明白了 阿里嘎多
