### ISSUE TITLE
开启了服务器之后 每次连接就Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by somethingforheheda** [linyacool/WebServer#144]
如题 
./WebServer -t 100 -p 8989 -l /home/wangning 开启服务器命令

**Comment by Handsome-bit** [comment]
./WebServer -t 100 -p 8989这样可以正常启动

**Comment by somethingforheheda** [comment]
改了之后还是有一样的错误啊

**Comment by somethingforheheda** [comment]
> ./WebServer -t 100 -p 8989这样可以正常启动

改了之后还是一样的错误。。

**Comment by NINEMINEsigma** [comment]
我也遇到了这样的问题,在启动后只要浏览器进入这个网页后就会如此崩溃
