### ISSUE TITLE
请教一下 /base/LogFile.cpp 中 reset 函数

### ISSUE THREAD

**Issue by bobbymly** [linyacool/WebServer#2]
/base/LogFile.cpp
19：    file_.reset(new AppendFile(basename));

这一句没看懂
file_ 是一个AppendFile类型的指针成员 却使用了 . 运算符
而且 ApendFile 类中 并没有定义 reset 方法

**Comment by linyacool** [comment]
@bobbymly file_ 成员是智能指针std::unique_ptr<AppendFile>, 智能指针本身是一个对象，所以有"."运算符，我们能用->是因为智能指针帮我们重载了->,才得以直接访问指针指向的内容
