### ISSUE TITLE
日志库压力测试

### ISSUE THREAD

**Issue by iLoveTangY** [linyacool/WebServer#24]
您好，您有没有对日志库进行压力测试呢？我看了`LoggingTest.cpp`，似乎只是简单的测试了一下接口，并没有计算性能指标之类的，还是我看漏了哪个地方呢？

**Comment by linyacool** [comment]
这个我没有测哎，你可以试一下

**Comment by iLoveTangY** [comment]
> 这个我没有测哎，你可以试一下

感谢回答，我测了下，每条消息120字节，在我的渣电脑上大概60万条消息/s，应该还算正常吧？

**Comment by linyacool** [comment]
> > 这个我没有测哎，你可以试一下
> 
> 感谢回答，我测了下，每条消息120字节，在我的渣电脑上大概60万条消息/s，应该还算正常吧？

我也没啥经验，我感觉还好

**Comment by iLoveTangY** [comment]
唔，感谢回答，还有个问题想问下，在日志库的实现代码中我发现很多可以使用栈变量的地方都使用了unique_ptr来指向一个堆上的数据，比如在`LogFile`中有
```c++
std::unique_ptr<MutexLock> mutex_; 
std::unique_ptr<AppendFile> file_;
```
不太明白为什么使用智能指针。。。

**Comment by linyacool** [comment]
@iLoveTangY 用栈变量是完全可以的，unique_ptr的好处是独自享有这个变量，不会传递到别处。

**Comment by iLoveTangY** [comment]
> @iLoveTangY 用栈变量是完全可以的，unique_ptr的好处是独自享有这个变量，不会传递到别处。
感谢回复，还有个问题想问下，TimerNode中计算超时时间时为什么要让秒对10000取余数？
```
expiredTime_ = (((now.tv_sec % 10000) * 1000) + (now.tv_usec / 1000)) + timeout;
```
这个超时时间应该是以毫秒来算的吧？

**Comment by linyacool** [comment]
@iLoveTangY 是毫秒，%10000是怕直接*1000乘爆了，模10000的是秒，10000秒作为超时时间已经足大了，真实情况不会超过这个。

**Comment by iLoveTangY** [comment]
> @iLoveTangY 是毫秒，%10000是怕直接*1000乘爆了，模10000的是秒，10000秒作为超时时间已经足大了，真实情况不会超过这个。

好的，非常感谢啦

**Comment by wstang35** [comment]
@linyacool 您好，请问超时时间计算让秒对10000取余数的话，10001秒不就比9999秒要小了么，这样定时器不会有问题吗？
