### ISSUE TITLE
关于 LoggingTest 

### ISSUE THREAD

**Issue by bobbymly** [linyacool/WebServer#3]
![zfxxxva9mi75 xv0 4a5b7](https://user-images.githubusercontent.com/18329217/37252025-7c134206-2555-11e8-8ef1-c1fc6a0a6e6f.png)

我试着测试了 LoggingTest 
不知道是我电脑的环境问题还是本来就这样？？
(注：make 过不了 我把Makefile 文件里的
![h4ez8wqn2_sh_xd06w l65](https://user-images.githubusercontent.com/18329217/37252062-f16d820a-2555-11e8-9526-c1f46b1f3f21.png)
改为
![dt9m_ fpr6wva37l 6a rw5](https://user-images.githubusercontent.com/18329217/37252112-9688abac-2556-11e8-903a-3e9b317f8ebd.png)

 ）

**Comment by linyacool** [comment]
@bobbymly 测的时候我直接写根目录了，你要测的话得给个权限 sudo ./LoggingTest
