### ISSUE TITLE
您好，关于成员函数的bind，我有一个疑问想请教一下

### ISSUE THREAD

**Issue by iLoveTangY** [linyacool/WebServer#41]
程序中大量使用了`std::bind`，但是除了一处地方，其他所有对成员函数执行`bind`时绑定的都是`this`指针，只有下面这一处使用的是`shared_from_this()`：
```c++
    else
    {
        //cout << "close with errors" << endl;
        loop_->runInLoop(bind(&HttpData::handleClose, shared_from_this()));
    }
```
具体位置在[这里](https://github.com/linyacool/WebServer/blob/master/WebServer/HttpData.cpp#L376)。
请问是如何作出这个判断，这里需要使用`shared_from_this()`的呢？或者是如何知道其他的地方只需要绑定`this`指针就好，不会有生存周期的问题的呢？感谢～

**Comment by linyacool** [comment]
HttpData一直是被shared_ptr封装的，所以用shared_from_this啊

**Comment by iLoveTangY** [comment]
> HttpData一直是被shared_ptr封装的，所以用shared_from_this啊

唔，好的，感谢。。
