### ISSUE TITLE
您好，关于Channel里的注册回调，有一些疑问想请教您

### ISSUE THREAD

**Issue by JingyuTongdlut** [linyacool/WebServer#43]
Channel类注册回调的参数，以写为例，参数为`std::function<void()>&& writeHandler`，然后再进行赋值的，我查看了muduo新的源码，同样以写为例，参数为`std::fnction<void> cb`，然后再通过`std::move`改为右值进行注册的，我想知道二者有什么分别，还有，关于注册回调典型写法，你有什么推荐的吗？

**Comment by linyacool** [comment]
@JingyuTongdlut 你看我传参数的时候都是临时构造的对象，效果是一样的，传的都是右值。
注册回调，无非就是固定好函数类型，然后给用户自定义，达到某个条件就出发这个函数，我觉得muduo的注册回调是非常经典的，也非常适合学习，我第一次接触注册回调就是从muduo这里学习的。

**Comment by JingyuTongdlut** [comment]
@linyacool 感谢解答
