### ISSUE TITLE
WebServer make 报错

### ISSUE THREAD

**Issue by tylercross** [linyacool/WebServer#5]
显示如下：
/usr/bin/ld: cannot find -lopencv_core
/usr/bin/ld: cannot find -lopencv_imgproc
/usr/bin/ld: cannot find -lopencv_highgui
/usr/bin/ld: cannot find -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
make: *** [WebServer] Error 1
没太看懂怎么就链接到opencv去了，请问执行完./build.sh，后执行make 前还有什么需要做的。

**Comment by tylercross** [comment]
安装了Opencv,make 通过！请问为何在这个里面链接opecv的库，是跟您之前做vr拼接相关吗

**Comment by linyacool** [comment]
这个。。。。build.sh执行完就编译完了，在上一层找。。根目录下的makefile是我以前写的，以前确实是想过要做一个图像相关的服务器来着，我有时间删掉它，好像给很多人造成误解了
