### ISSUE TITLE
你好，关于限制服务器的最大并发连接数

### ISSUE THREAD

**Issue by 469826336** [linyacool/WebServer#58]
if (accept_fd >= MAXFDS)
        {
            close(accept_fd);
            continue;
        }

请问这里accept_fd的值(调用accept()返回的值)和服务器并发连接数有什么必然联系吗，搜了很久也没找到想要的答案

**Comment by linyacool** [comment]
一个进程内，fd就是顺序递增的，所以涨到MAXFDS，差不多就是有了这么多的并发连接数，不是准确的限制，但是也差不多了

**Comment by 469826336** [comment]
明白了，比muduo的简洁太多了:D
