### ISSUE TITLE
访问www.linya.pub/hello时的问题

### ISSUE THREAD

**Issue by 469826336** [linyacool/WebServer#59]
今天看到HttpData.cpp的line529-544的代码，其中说明fileName_ == "hello"和fileName_ == "favicon.ico"两种情况的返回，于是我用firefox尝试访问了www.linya.pub/hello和www.linya.pub/favicon.ico，发现两种情况的响应时间差距有点大，hello的响应时间不确定，favicon.ico可以秒响应，感觉两种情况代码相差的不多，但响应时间对比下来感觉不应该这么悬殊，请问这样是正常的吗

**Comment by linyacool** [comment]
hello只用来测试的，没回复完整的http报文，所以你的浏览器是解析不出来的

**Comment by 469826336** [comment]
> 
> 
> hello只用来测试的，没回复完整的http报文，所以你的浏览器是解析不出来的
跟你讲个鬼故事，我的浏览器等了好久有几率返回Hello World

**Comment by linyacool** [comment]
@469826336 hhh 说明浏览器的代码写的不错
