### ISSUE TITLE
关于keepAlive的一个疑问

### ISSUE THREAD

**Issue by 469826336** [linyacool/WebServer#60]
if (keepAlive_) {
      events_ |= (EPOLLIN | EPOLLET);
      // events_ |= (EPOLLIN | EPOLLET | EPOLLONESHOT);
      int timeout = DEFAULT_KEEP_ALIVE_TIME;
      loop_->updatePoller(channel_, timeout);
    } else {
      // cout << "close normally" << endl;
      // loop_->shutdown(channel_);
      // loop_->runInLoop(bind(&HttpData::handleClose, shared_from_this()));
      events_ |= (EPOLLIN | EPOLLET);
      // events_ |= (EPOLLIN | EPOLLET | EPOLLONESHOT);
      int timeout = (DEFAULT_KEEP_ALIVE_TIME >> 1);
      loop_->updatePoller(channel_, timeout);
    }

你好，在处理连接时，如果报文中没有设置keepALive_，为什么不是像注释掉的代码那样关闭连接。这样做是通过增加系统开支，从而保持长连接吗

**Comment by linyacool** [comment]
这个你想怎么处理都行，我个人的理解是用户不设置，也不一定就是期望马上关闭连接的

**Comment by linyacool** [comment]
@469826336
