### ISSUE TITLE
close(-1)

### ISSUE THREAD

**Issue by zjh7890** [linyacool/WebServer#63]
文件：Util.cpp
函数：int socket_bind_listen(int port)
```
if (listen_fd == -1) {
        close(listen_fd);
        return -1;
    }
```
close(-1) 会造成：
  **errno: 9
  description: Bad file descriptor**
可能会覆盖有用的错误信息

**Comment by linyacool** [comment]
对，确实是个bug，我后面改一下，感谢提醒~
