### ISSUE TITLE
log打印问题

### ISSUE THREAD

**Issue by Raysuner** [linyacool/WebServer#78]
你好，我最近模仿muduo和你的代码写的一个简单的log，但是测试的时候发现测试文件中必须要加一定的延时log文件中才会有内容，否则一片空白，自己试了一下，是卡在等待日志那句cond_.waitForSeconds(flushInterval_)，然后程序就结束了。卡了我好几天了，还是没解决，所以想向你请教下

**Comment by linyacool** [comment]
异步日志就是这样的，如果你希望打印完马上结束程序，并且在log文件里看到，那你得实现一个同步日志模块

**Comment by Raysuner** [comment]
可能是我没讲清楚，我的意思不是说打印完就马上结束程序。我现在碰到的情况是即使程序结束后生成的log文件中也是空的。比如测试文件的main函数中有这么一段代码，按道理来说执行完循环后log文件中也该会有内容。但是我遇到的情况是必须要加usleep才会使log文件中有内容产生，而且时间还不能太小，否则程序结束后依旧不会有内容产生。我试过你的测试代码LoggingTest.cpp这个测试文件，在程序结束后，log文件中会有大量的内容。而我使用gdb的时候，也会在log文件中产生内容，估计是由于手动执行，速度对于计算机来说相当于sleep了，所以我一直找不到问题的所在
```cpp
void test(){
    for(int i = 0; i < 100000; ++i){
        LOG << i;
        //usleep(1000)
}
```

**Comment by Raysuner** [comment]
已解决，谢谢
