### ISSUE TITLE
异步日志问题

### ISSUE THREAD

**Issue by Raysuner** [linyacool/WebServer#81]
我编译了你的代码发现LoggingTest.cpp中如果不加入sleep(3)这条语句生成的webserver.log里面的内容有不少内容的丢失，我认为可能是程序在往磁盘写的过程中主程序结束了，造成了log文件内容的丢失，请问有什么解决办法吗？我本想着用latch来替换sleep的，但找不到og写完的时机。毕竟不是在测试文件中用sleep还是不太好

**Comment by linyacool** [comment]
异步日志就是可能会丢失最后的部分更新，这部分更新去core里面找就好了，如果你手动把进程停掉没产生core那是肯定找不到的
